import { addLocale, locale } from 'primereact/api';
import type { APIOptions, LocaleOptions } from 'primereact/api';

export const PRIME_REACT_LOCALE = 'vi';

export const primeReactConfig: Partial<APIOptions> = {
  ripple: true,
  inputStyle: 'outlined',
  locale: PRIME_REACT_LOCALE,
  autoZIndex: true,
  cssTransition: true,
  zIndex: {
    modal: 1100,
    overlay: 1000,
    menu: 1000,
    tooltip: 1100,
    toast: 1200,
  },
};

export const appIcons = {
  home: 'pi pi-home',
  dashboard: 'pi pi-chart-line',
  user: 'pi pi-user',
  users: 'pi pi-users',
  doctor: 'pi pi-briefcase',
  appointment: 'pi pi-calendar',
  calendar: 'pi pi-calendar-clock',
  search: 'pi pi-search',
  add: 'pi pi-plus',
  edit: 'pi pi-pencil',
  delete: 'pi pi-trash',
  save: 'pi pi-save',
  cancel: 'pi pi-times',
  close: 'pi pi-times',
  login: 'pi pi-sign-in',
  logout: 'pi pi-sign-out',
  email: 'pi pi-envelope',
  password: 'pi pi-lock',
  phone: 'pi pi-phone',
  location: 'pi pi-map-marker',
  notification: 'pi pi-bell',
  setting: 'pi pi-cog',
  loading: 'pi pi-spin pi-spinner',
} as const;

const vietnameseLocale: LocaleOptions = {
  startsWith: 'Bắt đầu với',
  contains: 'Chứa',
  notContains: 'Không chứa',
  endsWith: 'Kết thúc với',
  equals: 'Bằng',
  notEquals: 'Không bằng',
  noFilter: 'Không lọc',
  lt: 'Nhỏ hơn',
  lte: 'Nhỏ hơn hoặc bằng',
  gt: 'Lớn hơn',
  gte: 'Lớn hơn hoặc bằng',
  dateIs: 'Ngày là',
  dateIsNot: 'Ngày không phải',
  dateBefore: 'Ngày trước',
  dateAfter: 'Ngày sau',
  clear: 'Xóa',
  apply: 'Áp dụng',
  matchAll: 'Khớp tất cả',
  matchAny: 'Khớp bất kỳ',
  addRule: 'Thêm điều kiện',
  removeRule: 'Xóa điều kiện',
  accept: 'Đồng ý',
  reject: 'Từ chối',
  choose: 'Chọn',
  upload: 'Tải lên',
  cancel: 'Hủy',
  completed: 'Hoàn tất',
  pending: 'Đang chờ',
  dayNames: ['Chủ nhật', 'Thứ hai', 'Thứ ba', 'Thứ tư', 'Thứ năm', 'Thứ sáu', 'Thứ bảy'],
  dayNamesShort: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
  dayNamesMin: ['CN', 'T2', 'T3', 'T4', 'T5', 'T6', 'T7'],
  monthNames: [
    'Tháng 1',
    'Tháng 2',
    'Tháng 3',
    'Tháng 4',
    'Tháng 5',
    'Tháng 6',
    'Tháng 7',
    'Tháng 8',
    'Tháng 9',
    'Tháng 10',
    'Tháng 11',
    'Tháng 12',
  ],
  monthNamesShort: [
    'Thg 1',
    'Thg 2',
    'Thg 3',
    'Thg 4',
    'Thg 5',
    'Thg 6',
    'Thg 7',
    'Thg 8',
    'Thg 9',
    'Thg 10',
    'Thg 11',
    'Thg 12',
  ],
  today: 'Hôm nay',
  weekHeader: 'Tuần',
  firstDayOfWeek: 1,
  dateFormat: 'dd/mm/yy',
  weak: 'Yếu',
  medium: 'Trung bình',
  strong: 'Mạnh',
  passwordPrompt: 'Nhập mật khẩu',
  emptyMessage: 'Không có dữ liệu',
  emptyFilterMessage: 'Không tìm thấy kết quả',
  emptySearchMessage: 'Không tìm thấy kết quả',
  emptySelectionMessage: 'Chưa chọn mục nào',
  selectionMessage: 'Đã chọn {0} mục',
  searchMessage: 'Có {0} kết quả',
  fileChosenMessage: 'Đã chọn {0} tệp',
  noFileChosenMessage: 'Chưa chọn tệp',
  chooseDate: 'Chọn ngày',
  chooseMonth: 'Chọn tháng',
  chooseYear: 'Chọn năm',
  prevDecade: 'Thập kỷ trước',
  nextDecade: 'Thập kỷ sau',
  prevYear: 'Năm trước',
  nextYear: 'Năm sau',
  prevMonth: 'Tháng trước',
  nextMonth: 'Tháng sau',
  prevHour: 'Giờ trước',
  nextHour: 'Giờ sau',
  prevMinute: 'Phút trước',
  nextMinute: 'Phút sau',
  prevSecond: 'Giây trước',
  nextSecond: 'Giây sau',
};

export const setupPrimeReact = () => {
  addLocale(PRIME_REACT_LOCALE, vietnameseLocale);
  locale(PRIME_REACT_LOCALE);
};